name: Release on demand

on:
  workflow_dispatch:
    inputs:
      releaseVersion:
        description: "Version to release"
        required: true
        default: "X.Y.Z"
        type: string
      snapshotVersion:
        description: "Snapshot version after release"
        required: true
        default: "X.Y.Z-SNAPSHOT"
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out
      uses: actions/checkout@v4
    - name: Set Github identity
      run: |
        git config --global user.name clojure-build
        git config --global user.email "clojure-build@users.noreply.github.com"
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        java-version: 21
        distribution: 'temurin'
        cache: 'maven'
        server-id: central
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        gpg-private-key: ${{ secrets.CENTRAL_GPG_SECRET_KEY }}
        gpg-passphrase: GPG_PASSPHRASE
    - name: Publish to Maven Server
      run: mvn -ntp -B -DreleaseVersion=${{ github.event.inputs.releaseVersion }} -DdevelopmentVersion=${{ github.event.inputs.snapshotVersion }} -DskipStaging=true -Psign -Dmaven.test.skip=true release:prepare release:perform
      env:
        MAVEN_USERNAME: ${{ secrets.CENTRAL_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.CENTRAL_PASSWORD }}
        GPG_PASSPHRASE: ${{ secrets.CENTRAL_GPG_SECRET_KEY_PASSWORD }}
    - name: Tag
      run: |
        git push --tags
        git push
